import pymunk

TPS = 15

# COL_FILTERS
COL_ON_WATER = pymunk.ShapeFilter(categories=1, mask=57)
COL_ON_GROUND = pymunk.ShapeFilter(categories=2, mask=10)
COL_ON_WATER_GROUND = pymunk.ShapeFilter(categories=3, mask=11)
COL_S = pymunk.ShapeFilter(categories=8)
COL_B = pymunk.ShapeFilter(categories=16)
COL_C = pymunk.ShapeFilter(categories=32)

COF_WATER_RESISTANCE = 250
COF_WATER_RESISTANCE_MOMENT = 2
COF_WATER_SURFACE_FRICTION = 20
COLTYPE_PROJECTILE = 2
COLTYPE_VEHICLE = 1
COF_GROUND_RESISTANCE = 5

DO_FRIENDLY_FIRE = False
DO_FRIENDLY_BUILDINGS_DAMAGE = False

COF_EX_DMG_PER_AREA = 10000
COF_PR_DMG_PER_AREA = 2500
COF_HP_PER_AREA = 1000
COF_MASS_PER_AREA = 20
COF_PIERCING_DURABILITY = 10

# COL_TYPES
ACCESSABLE_GROUND = 0
INACCESSABLE_GROUND = 1
# BRIDGE_GROUND = 2
INDESTRUCTIBLE = 3
DESTRUCTIBLE = 4

BUILDING_HP_PER_REPAIR = 0.25

MARK_ID_VEHICLE = 0
MARK_ID_BASE = 1
MARK_ID_SP = 2
MARK_ID_POINT = 3
MARK_ID_ARROW = 4
MARK_ID_RADAR = 5
MARK_ID_OBSERVED_ZONE = 6
